### ISSUE TITLE
@nuxtjs/tailwindcss has dependency issue related to @nuxt/kit

### ISSUE THREAD

**Issue by dkrdj8989** [nuxt/postcss8#38]

**Comment by mulhoon** [comment]
I've had the same since yesterday. A fresh install fails on `yarn dev`

Node: v16.13.0, MacOS Monterey 12.6

Setup:
```
create-nuxt-app v5.0.0
✨  Generating Nuxt.js project in nuxt-what
? Project name: nuxt-what
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: Tailwind CSS
? Template engine: HTML
? Nuxt.js modules: Axios - Promise based HTTP client
? Linting tools: Prettier
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: Git
yarn run v1.22.17
```

Result:
```
$ nuxt
ℹ Using default Tailwind CSS file from runtime/tailwind.css                                                                                            nuxt:tailwindcss 10:25:00

 FATAL  Cannot destructure property 'nuxt' of 'this' as it is undefined.                                                                                                10:25:00

  at postcss8Module (node_modules/@nuxt/postcss8/dist/index.js:15:10)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:416:9)
  at async setup (node_modules/@nuxtjs/tailwindcss/dist/module.mjs:186:7)
  at async ModuleContainer.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:20)
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:51:7)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭─────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                 │
   │   ✖ Nuxt Fatal Error                                                            │
   │                                                                                 │
   │   TypeError: Cannot destructure property 'nuxt' of 'this' as it is undefined.   │
   │                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────╯
```
